name: Selenium Tests

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  selenium-tests:
    runs-on: ubuntu-latest  # Use Ubuntu as the OS for the runner

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Step 3: Cache Maven dependencies (optional, speeds up builds)
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      # Step 4: Install dependencies using Maven
      - name: Install dependencies
        run: mvn install

      # Step 5: Install Chrome for Selenium
      - name: Install Chrome
        run: sudo apt-get install -y chromium-browser

      # Step 6: Run Selenium tests using Maven
      - name: Run Selenium tests
        run: mvn test
